---
sidebar: sidebar
permalink: ai/oai_bpod_architecture.html
keywords: NetApp AI, AI, Artificial Intelligence, ML, Machine Learning, NVIDIA, NVIDIA AI Enterprise, NVIDIA BasePOD, NVIDIA DGX
summary: ONTAP AI with NVIDIA DGX BasePOD - Conclusion
---

= ONTAP AI with NVIDIA DGX BasePOD - Conclusion
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

link:oai_bpod_sizing.html[Previous: Sizing Guidance.]

== Conclusion

The DGX BasePOD architecture is a next-generation deep learning platform that requires equally advanced storage and data management capabilities. By combining DGX BasePOD with NetApp AFF systems, this architecture can be implemented at almost any scale, from a single DGX A100 paired with an AFF A2500 storage system up to potentially 48 DGX A100 systems on a 24-node AFF A800 cluster. Combined with the superior cloud integration and software-defined capabilities of NetApp ONTAP, AFF enables a full range of data pipelines that spans the edge, the core, and the cloud for successful DL projects.

link:oai_bpod_additional_information.html[Next: Additional Information.]